name: Publish

on: [workflow_dispatch]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Pack
      run: dotnet pack -c Release -o out
    
    - name: Publish StepFlow
      run: dotnet nuget push ./out/StepFlow.0.0.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_ORG_TOKEN}}

    - name: Publish StepFlow.Contracts
      run: dotnet nuget push ./out/StepFlow.Contracts.0.0.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_ORG_TOKEN}}